### PR TITLE
[#165632607] Fix http url for Milano/AreaB service

### PR DESCRIPTION
**Pull request by Alex193a**
Fixed the http url for Milano/AreaB service.

https://www.pivotaltracker.com/n/projects/2048617/stories/165632607

### CODE REVIEW

**Comment by Undermaken** [comment]
@Alex193a Did you test all urls changed?

**Comment by Alex193a** [comment]
@Undermaken Yes I've tested all URLs, the services.yml has been updated in [the last commit](https://github.com/teamdigitale/io-services-metadata/pull/41/commits/c1f33615a36f657e47ed5761a503c16f04bae05a).

**Comment by Undermaken** [comment]
@Alex193a I'm quite sure you don't follow the right procedure to edit services
https://github.com/teamdigitale/io-services-metadata/blob/master/README.md
To edit/add/remove a service you have to change services.yml file, then you can generate automatically the jsons files

> @Undermaken Yes I've tested all URLs, the services.yml has been updated in [the last commit](https://github.com/teamdigitale/io-services-metadata/pull/41/commits/c1f33615a36f657e47ed5761a503c16f04bae05a).

Good! 
Anyway now there are jsons generated automatically and others edited manually.
Try to restore the ones edited manually (or delete all jsons and generate them again)

**Comment by Alex193a** [comment]
@Undermaken I've restored all files, now only the services.yml has been edited in this PR.

**Comment by Alex193a** [comment]
@Undermaken Done!

**Pull request merged**
